import React from 'react'

export const CircleLoading = ({ size, noBackground }) => (
  <div style={{
    width: noBackground ? 'unset' : '100%',
    height: noBackground ? 'unset' : '100%',
    backgroundColor: noBackground ? 'none' : 'none',
    opacity: '0.8',
    minHeight: noBackground ? 'unset' : '10vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  }}
  >
    <svg
      xmlns="http://www.w3.org/2000/svg"
      style={{
        margin: 'unset auto', background: 'none', display: 'block', shapeRendering: 'auto',
      }}
      width={size}
      height={size}
      viewBox="0 0 100 100"
      preserveAspectRatio="xMidYMid"
    >
      <circle cx="50" cy="50" fill="none" stroke="lightgray" strokeWidth="8" r="41" strokeDasharray="193.20794819577225 66.40264939859075">
        <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1s" values="0 50 50;360 50 50" keyTimes="0;1" />
      </circle>
      {/* <!-- [ldio] generated by https://loading.io/ --> */}
    </svg>

  </div>
)
