export const NewFollower = 'follow'
export const CommentCivilityGiven = 'comment_civility'
export const TribunalSelection = 'tribunal_selection'
export const UserContentReported = 'user_content_reported'
export const CommentLike = 'comment_like'
export const SpaceLike = 'space_like'
