export const CAPTCHA_VERIFIED = 'CAPTCHA_VERIFIED'
export const FACE_ID_VERIFIED = 'FACE_ID_VERIFIED'
export const FACE_ID_AND_CAPTCHA_VERIFIED = 'FACE_ID_AND_CAPTCHA_VERIFIED'
export const NO_VERIFICATION = 'NO_VERIFICATION'
